---
- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Ensure tftp server
  ansible.builtin.package:
    name: "{{ pxeserver_tftp_package }}"
    state: present

- name: Ensure syslinux
  ansible.builtin.package:
    name: "{{ pxeserver_syslinux_package }}"
    state: present

- name: Ensure tftp.socket
  ansible.builtin.service:
    name: "{{ pxeserver_tftp_service }}"
    state: started
    enabled: yes

- name: Ensure tftpboot directory
  ansible.builtin.file:
    dest: "{{ pxeserver_tftproot_location }}/"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Ensure tftpboot configuration
  ansible.builtin.template:
    src: default.j2
    dest: "{{ pxeserver_tftproot_location }}/default"
    owner: root
    group: root
    mode: 0644
